sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - mercurial
install:
- git+https://github.com/sphinx-doc/sphinx
- pip install sphinx_bootstrap_theme
script:
- "./pull-examples.sh"
- GH_USER=LoyolaChicagoBooks GH_REPO=introcs-csharp "./gh-pages.sh"
env:
  global:
    secure: Gi/sb53XMBl0lkZNLbTfXMX1v3xlsPmMVgadDO7cIrp4MjFYsDy/Ym+0pxxkgnLhdCRz6VSvMAVchsIHMOEDAz3n4nVtJxFAkzhoXEjJELpzA0bsV/Lkohqw0gA4QPpl4aUH8mSYZYpeITRCKNfWVaaVG2qQHrC1HFroaXniGP0=
